que.2 ans
Application software. The most common type of software, application software is a computer software package that performs a specific function for a user, or in some cases, for another application. ...
System software. ...
Driver software. ...
Middleware. ...
Programming software.